### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by gafstar** [soft-nougat/dqw-ivves_structured#1]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://share.streamlit.io/soft-nougat/dqw-ivves_structured/main/app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.
Check out this ![image](https://user-images.githubusercontent.com/42951228/157305823-c4a4c756-6020-463f-8e8a-9df62230d614.png)

**Comment by soft-nougat** [comment]
Thank you @gafstar! Rebooted. Seems like the traffic is too much to handle. I will look into the performance in the coming days. 😺

**Comment by gafstar** [comment]
Hey Tia, thanks for the update. It is great making use of different python packages within the streamlit app.
