### ISSUE TITLE
issues while running the tabular data section locally

### ISSUE THREAD

**Issue by Flugbanane97** [soft-nougat/dqw-ivves_structured#7]
![image](https://user-images.githubusercontent.com/65468211/171012224-c9a7ba6e-c298-4384-90ea-f669f479b1f5.png)

 I got some issues while opening the tabular data section. Everything else is working fine. I was running the app.py file locally.

**Comment by soft-nougat** [comment]
See https://github.com/soft-nougat/dqw-ivves_structured/issues/8#issue-1252816555
