### ISSUE TITLE
issues while running the tabular data section

### ISSUE THREAD

**Issue by Flugbanane97** [soft-nougat/dqw-ivves_structured#8]
![image](https://user-images.githubusercontent.com/65468211/171012224-c9a7ba6e-c298-4384-90ea-f669f479b1f5.png)

 I got some issues while opening the tabular data section. Everything else is working fine. I was running the app.py file locally.

**Comment by soft-nougat** [comment]
Thanks @Flugbanane97! I redeployed it. Let me know if there are more issues.

**Comment by soft-nougat** [comment]
There was an issue in the package dependencies with streamlit cloud, fixed it by adding a line in requirements for protobuf

https://discuss.streamlit.io/t/typeerror-descriptors-cannot-not-be-created-directly/25639/5
